services:
  app:
    build: .
    container_name: pytorch_dev_env
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true